// Auto-generated by the OpenUSDKit binary slice. Empty by design: existing only
// to carry the OpenUSD product dependency into the SwiftUsdShellOpenUSD product
// so adopters do not have to declare OpenUSD/SwiftUsd themselves.
//
// Xcode can pre-plan SwiftPM package targets for Intel macOS even when the
// consuming app is Apple Silicon-only. The OpenUSD binary bundle is arm64-only,
// so only import it for arm64 package slices; accidental x86_64 slices compile
// an empty shim and are excluded by the final app/archive settings.
#if arch(arm64)
@_exported import OpenUSD
#endif
