// Auto-generated by the OpenUSDKit binary slice. Empty by design: existing only
// to carry the OpenUSD product dependency into the SwiftUsdShellOpenUSD product
// so adopters do not have to declare OpenUSD/SwiftUsd themselves.
@_exported import OpenUSD
